Test-cases

title title title

participant participant participant as p

# comment

alt alt

    activate activate
    deactivate deactivate
    
else else
    
    note note
    end end

    state state
    end end

    loop loop
    end end

    parallel parallel

    ref ref
    end end

end end

opt opt
end end    

end note end note
end ref end ref
end state end state
