Test-cases

title title title

participant participant participant as p

# comment

alt alt

    activate activate
    deactivate deactivate
    
else else
    
    note note
    end end

    state state
    end end

    ref ref
    end ref
    
    loop loop
    end end

    parallel parallel
    
end end

opt opt
end end
    
ref ref 